import Phaser from "phaser";
import { Client } from "@colyseus/sdk";
import { GAME } from "../../shared/src/constants";
import "./style.css";

const app = document.querySelector<HTMLDivElement>("#app");
if (!app) throw new Error("Missing #app element");
const serverUrl = import.meta.env.PROD ? location.origin : `${location.protocol}//${location.hostname}:${import.meta.env.VITE_GAME_SERVER_PORT ?? "3000"}`;

app.innerHTML = `<div class="shell">
  <header class="topbar"><div><div class="eyebrow">XPGame // HORDE PROTOCOL</div><h1>Co-op survival. No limits.</h1></div><div id="connection" class="status">OFFLINE</div></header>
  <section class="controls lobbyBar">
    <input id="name" maxlength="18" value="Player" aria-label="Spielername" placeholder="Spielername" />
    <select id="map"><option value="neon_city">Neon City</option><option value="desert_ruins">Desert Ruins</option><option value="frozen_outpost">Frozen Outpost</option><option value="toxic_swamp">Toxic Swamp</option></select>
    <select id="weapon"><option value="rifle">Rifle</option><option value="shotgun">Shotgun</option><option value="smg">SMG</option><option value="cannon">Cannon</option><option value="arc">Arc</option></select>
    <input id="roomCode" maxlength="32" placeholder="Room-Code (optional)" aria-label="Room code" />
    <button id="connect" type="button">QUICK MATCH</button><button id="join" type="button">JOIN ROOM</button><button id="ready" type="button" disabled>READY</button><button id="settings" type="button">⚙</button>
  </section>
  <div id="game" class="game"></div>
  <aside class="sidepanel">
    <div><span>Map</span><strong id="mapName">Neon City</strong></div><div><span>Room</span><strong id="roomLabel">—</strong></div><div><span>Phase</span><strong id="phase">LOBBY</strong></div><div><span>Event</span><strong id="event">—</strong></div><div><span>Wave</span><strong id="wave">0</strong></div><div><span>Players</span><strong id="players">0 / ${GAME.maxPlayers}</strong></div><div><span>Level</span><strong id="level">1</strong></div><div><span>XP</span><strong id="xp">0 / 100</strong></div><div><span>HP</span><strong id="hp">100 / 100</strong></div><div><span>Lives</span><strong id="lives">3</strong></div><div><span>Kills</span><strong id="kills">0</strong></div><div><span>Coins</span><strong id="coins">0</strong></div><div><span>Score</span><strong id="score">0</strong></div>
    <div class="hint">WASD/Arrows bewegen · Maus zielen · Linksklick halten · 1-3 Upgrade · Revive bei Downed-Spielern stehen</div>
    <div class="board"><div class="eyebrow">LEADERBOARD</div><div id="leaderboard"></div></div>
  </aside>
  <div id="upgradeOverlay" class="overlay hidden" aria-live="polite"><div class="upgradePanel"><div class="eyebrow">LEVEL UP</div><h2>Choose an upgrade</h2><div id="upgradeCards" class="upgradeCards"></div></div></div>
  <div id="settingsOverlay" class="overlay hidden"><div class="upgradePanel settingsPanel"><div class="eyebrow">SETTINGS</div><h2>Game settings</h2><label><input id="mute" type="checkbox" /> Mute audio</label><label><input id="particles" type="checkbox" checked /> Particles</label><button id="closeSettings">CLOSE</button></div></div>
  <div id="gameMessage" class="gameMessage hidden"></div>
</div>`;

const el = <T extends Element>(selector: string) => document.querySelector<T>(selector)!;
const connectionEl = el<HTMLDivElement>("#connection"); const phaseEl = el<HTMLElement>("#phase"); const eventEl = el<HTMLElement>("#event"); const waveEl = el<HTMLElement>("#wave"); const playersEl = el<HTMLElement>("#players"); const levelEl = el<HTMLElement>("#level"); const xpEl = el<HTMLElement>("#xp"); const hpEl = el<HTMLElement>("#hp"); const livesEl = el<HTMLElement>("#lives"); const killsEl = el<HTMLElement>("#kills"); const coinsEl = el<HTMLElement>("#coins"); const scoreEl = el<HTMLElement>("#score"); const mapNameEl = el<HTMLElement>("#mapName"); const roomLabelEl = el<HTMLElement>("#roomLabel"); const leaderboardEl = el<HTMLDivElement>("#leaderboard"); const nameInput = el<HTMLInputElement>("#name"); const mapSelect = el<HTMLSelectElement>("#map"); const weaponSelect = el<HTMLSelectElement>("#weapon"); const roomCodeInput = el<HTMLInputElement>("#roomCode"); const connectButton = el<HTMLButtonElement>("#connect"); const joinButton = el<HTMLButtonElement>("#join"); const readyButton = el<HTMLButtonElement>("#ready"); const settingsButton = el<HTMLButtonElement>("#settings"); const settingsOverlay = el<HTMLDivElement>("#settingsOverlay"); const muteInput = el<HTMLInputElement>("#mute"); const particlesInput = el<HTMLInputElement>("#particles"); const closeSettings = el<HTMLButtonElement>("#closeSettings"); const overlay = el<HTMLDivElement>("#upgradeOverlay"); const upgradeCards = el<HTMLDivElement>("#upgradeCards"); const messageEl = el<HTMLDivElement>("#gameMessage");
let room: any = null; let localSessionId = ""; let ready = false; let lastUpgradeSignature = ""; let firing = false; let lastWave = 0; let lastPhase = ""; let audioContext: AudioContext | null = null;
const upgradeCatalog: Record<string, { title: string; description: string; rarity: string }> = { heavy_bullets: { title: "Heavy Bullets", description: "+20% damage", rarity: "COMMON" }, rapid_fire: { title: "Rapid Fire", description: "12% faster attacks", rarity: "COMMON" }, twin_shot: { title: "Twin Shot", description: "+1 projectile", rarity: "UNCOMMON" }, piercing: { title: "Piercing", description: "+1 pierce", rarity: "UNCOMMON" }, velocity: { title: "Velocity", description: "+20% projectile speed", rarity: "COMMON" }, adrenaline: { title: "Adrenaline", description: "+15% movement speed", rarity: "COMMON" }, magnet: { title: "Magnet", description: "+45 pickup radius", rarity: "COMMON" }, vitality: { title: "Vitality", description: "+25 max HP and heal", rarity: "COMMON" }, armor: { title: "Armor Plating", description: "Reduce incoming damage", rarity: "UNCOMMON" }, critical: { title: "Critical Strike", description: "+8% crit chance", rarity: "RARE" }, deadeye: { title: "Deadeye", description: "+35% crit damage", rarity: "RARE" }, overclock: { title: "Overclock", description: "18% faster attacks and +8% damage", rarity: "EPIC" } };
function beep(frequency: number, duration = .06, type: OscillatorType = "square") { if (muteInput.checked) return; try { audioContext ??= new AudioContext(); const osc = audioContext.createOscillator(); const gain = audioContext.createGain(); osc.type = type; osc.frequency.value = frequency; gain.gain.setValueAtTime(.03, audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audioContext.currentTime + duration); osc.connect(gain).connect(audioContext.destination); osc.start(); osc.stop(audioContext.currentTime + duration); } catch {} }
function showMessage(text: string) { messageEl.textContent = text; messageEl.classList.remove("hidden"); window.setTimeout(() => messageEl.classList.add("hidden"), 1800); }
function saveMeta(state: any) { const local = state.players.get(localSessionId); if (!local) return; const current = JSON.parse(localStorage.getItem("xpgameMeta") || '{"victories":0,"bestWave":0,"bestKills":0,"coins":0}') as Record<string, number>; current.coins = Math.max(current.coins ?? 0, Number(local.coins ?? 0)); current.bestWave = Math.max(current.bestWave ?? 0, Number(state.wave ?? 0)); current.bestKills = Math.max(current.bestKills ?? 0, Number(local.kills ?? 0)); localStorage.setItem("xpgameMeta", JSON.stringify(current)); }

class MainScene extends Phaser.Scene {
  private players = new Map<string, Phaser.GameObjects.Arc>(); private enemies = new Map<string, Phaser.GameObjects.Arc>(); private projectiles = new Map<string, Phaser.GameObjects.Arc>(); private xpDrops = new Map<string, Phaser.GameObjects.Arc>(); private loot = new Map<string, Phaser.GameObjects.Arc>(); private particles = new Set<Phaser.GameObjects.GameObject>();
  constructor() { super("main"); }
  create() { this.cameras.main.setBackgroundColor("#070b16"); this.add.rectangle(GAME.width / 2, GAME.height / 2, GAME.width, GAME.height, 0x0b1222); this.add.grid(GAME.width / 2, GAME.height / 2, GAME.width, GAME.height, 64, 64, 0x101827, 1, 0x1b2a48, .24); }
  sync(state: any) {
    this.syncMap(state.players, this.players, (id: string, p: any) => { const c = this.add.circle(p.x, p.y, 18, id === localSessionId ? 0x67e8f9 : 0x8b5cf6); c.setStrokeStyle(p.downed ? 4 : 3, p.downed ? 0xef4444 : 0xffffff, .85); return c; });
    this.syncMap(state.enemies, this.enemies, (_id: string, e: any) => { const colors: Record<string, number> = { basic: 0xf43f5e, fast: 0xfb923c, tank: 0x94a3b8, ranged: 0xa78bfa, swarm: 0xfda4af, splitter: 0xf97316, healer: 0x4ade80, elite: 0xfacc15, miniboss: 0xfb7185, boss: 0xef4444 }; const c = this.add.circle(e.x, e.y, e.radius ?? 16, colors[e.kind] ?? 0xf43f5e); c.setStrokeStyle(e.boss ? 6 : e.elite ? 3 : 2, 0xffffff, .8); return c; });
    this.syncMap(state.projectiles, this.projectiles, (_id: string, p: any) => this.add.circle(p.x, p.y, 5, 0xfef08a));
    this.syncMap(state.xpDrops, this.xpDrops, (_id: string, drop: any) => this.add.circle(drop.x, drop.y, 6, 0x22d3ee));
    this.syncMap(state.loot, this.loot, (_id: string, drop: any) => { const c = this.add.circle(drop.x, drop.y, drop.kind === "weapon" ? 9 : 7, drop.kind === "weapon" ? 0xe879f9 : 0xfacc15); c.setStrokeStyle(2, 0xffffff, .9); return c; });
    for (const p of this.particles) if (!(p as any).active) this.particles.delete(p);
  }
  burst(x: number, y: number, size = 20) { if (!particlesInput.checked) return; for (let i = 0; i < 5; i += 1) { const c = this.add.circle(x, y, 2 + Math.random() * 4, 0xffffff, .9); this.particles.add(c); this.tweens.add({ targets: c, x: x + (Math.random() - .5) * size, y: y + (Math.random() - .5) * size, alpha: 0, duration: 220 + Math.random() * 180, onComplete: () => c.destroy() }); } }
  private syncMap<T extends Phaser.GameObjects.GameObject>(source: any, target: Map<string, T>, create: (id: string, data: any) => T) { const seen = new Set<string>(); source.forEach((data: any, id: string) => { seen.add(id); let marker = target.get(id); if (!marker) { marker = create(id, data); target.set(id, marker); } (marker as any).setPosition(data.x, data.y); }); for (const [id, marker] of target) { if (!seen.has(id)) { marker.destroy(); target.delete(id); } } }
}
const game = new Phaser.Game({ type: Phaser.AUTO, parent: "game", width: GAME.width, height: GAME.height, scene: [MainScene], render: { antialias: true, pixelArt: false }, scale: { mode: Phaser.Scale.FIT, autoCenter: Phaser.Scale.CENTER_BOTH } });

function renderUpgradeChoices(ids: string[]) { const signature = ids.join("|"); if (signature === lastUpgradeSignature || ids.length === 0) return; lastUpgradeSignature = signature; overlay.classList.remove("hidden"); beep(880, .16, "sine"); upgradeCards.innerHTML = ""; ids.forEach((id, index) => { const info = upgradeCatalog[id] ?? { title: id, description: "Upgrade", rarity: "COMMON" }; const b = document.createElement("button"); b.className = "upgradeCard"; b.type = "button"; b.innerHTML = `<span class="rarity">${info.rarity}</span><strong>${index + 1}. ${info.title}</strong><span>${info.description}</span>`; b.addEventListener("click", () => { room?.send("chooseUpgrade", id); overlay.classList.add("hidden"); lastUpgradeSignature = ""; beep(520, .1, "sine"); }); upgradeCards.appendChild(b); }); }
function renderLeaderboard(value: string) { try { const rows = JSON.parse(value) as Array<{name: string; score: number; kills: number; level: number}>; leaderboardEl.innerHTML = rows.length ? rows.map((r, i) => `<div class="boardRow"><span>#${i + 1} ${r.name}</span><strong>${Math.floor(r.score)}</strong></div>`).join("") : `<span class="muted">Noch keine Scores</span>`; } catch { leaderboardEl.textContent = "—"; } }

async function join(mode: "quick" | "room") {
  connectionEl.textContent = "CONNECTING..."; connectButton.disabled = true; joinButton.disabled = true;
  try {
    const client = new Client(serverUrl);
    const options = { name: nameInput.value.trim() || "Player", mapId: mapSelect.value };
    room = mode === "room" ? await client.joinById(roomCodeInput.value.trim(), options) : await client.joinOrCreate("game", options);
    localSessionId = room.sessionId; ready = false; readyButton.textContent = "READY"; readyButton.disabled = false; connectionEl.textContent = "CONNECTED"; lastPhase = ""; beep(660, .08, "sine");
    room.onStateChange((state: any) => {
      const phase = String(state.phase); phaseEl.textContent = phase.toUpperCase(); eventEl.textContent = String(state.event || "—").replace(/_/g, " ").toUpperCase(); waveEl.textContent = String(state.wave); playersEl.textContent = `${state.players.size} / ${GAME.maxPlayers}`; mapNameEl.textContent = String(state.mapName); roomLabelEl.textContent = String(state.roomCode || "—"); renderLeaderboard(String(state.leaderboard || "[]"));
      if (state.wave !== lastWave && state.wave > 0) { lastWave = state.wave; showMessage(`WAVE ${state.wave}`); beep(220 + Math.min(8, state.wave) * 35, .12, "sawtooth"); }
      if (phase !== lastPhase) { if (phase === "game_over") { overlay.classList.add("hidden"); showMessage("ALL PLAYERS DOWN — GAME OVER"); beep(120, .35, "sawtooth"); } if (phase === "victory") { overlay.classList.add("hidden"); showMessage("VICTORY — RUN COMPLETE"); beep(880, .12, "sine"); window.setTimeout(() => beep(1320, .25, "sine"), 110); } lastPhase = phase; }
      const local = state.players.get(localSessionId); if (local) { levelEl.textContent = String(local.level); xpEl.textContent = `${Math.floor(local.xp)} / ${Math.floor(local.xpToNext)}`; hpEl.textContent = `${Math.ceil(local.hp)} / ${Math.ceil(local.maxHp)}`; livesEl.textContent = String(local.lives); killsEl.textContent = String(local.kills); coinsEl.textContent = String(local.coins); scoreEl.textContent = String(Math.floor(local.score)); if (local.downed) showMessage(`DOWNED — REVIVE / ${Math.ceil(local.respawnMs / 1000)}s`); if (local.upgradeChoices && local.upgradeChoices !== "[]" && local.upgradeChoices !== "pending") { try { renderUpgradeChoices(JSON.parse(local.upgradeChoices) as string[]); } catch { overlay.classList.add("hidden"); } } saveMeta(state); }
      const scene = game.scene.getScene("main") as MainScene; scene.sync(state);
      if (state.event) scene.burst(GAME.width / 2, 90, 90);
    });
    room.onLeave(() => { firing = false; lastPhase = ""; lastUpgradeSignature = ""; ready = false; readyButton.textContent = "READY"; connectionEl.textContent = "DISCONNECTED"; connectButton.disabled = false; joinButton.disabled = false; readyButton.disabled = true; room = null; overlay.classList.add("hidden"); showMessage("DISCONNECTED"); });
  } catch (error) { console.error(error); connectionEl.textContent = "CONNECTION ERROR"; connectButton.disabled = false; joinButton.disabled = false; }
}
connectButton.addEventListener("click", () => void join("quick")); joinButton.addEventListener("click", () => void join("room"));
readyButton.addEventListener("click", () => { if (!room || lastPhase !== "lobby") return; ready = !ready; readyButton.textContent = ready ? "READY ✓" : "READY"; room.send("ready", ready); room.send("weapon", { weapon: weaponSelect.value }); beep(500, .05, "sine"); });
settingsButton.addEventListener("click", () => settingsOverlay.classList.remove("hidden")); closeSettings.addEventListener("click", () => settingsOverlay.classList.add("hidden"));
muteInput.checked = localStorage.getItem("xpgameMute") === "1"; particlesInput.checked = localStorage.getItem("xpgameParticles") !== "0"; muteInput.addEventListener("change", () => localStorage.setItem("xpgameMute", muteInput.checked ? "1" : "0")); particlesInput.addEventListener("change", () => localStorage.setItem("xpgameParticles", particlesInput.checked ? "1" : "0"));
const keys = new Set<string>(); window.addEventListener("keydown", event => { keys.add(event.key.toLowerCase()); if (/^[1-3]$/.test(event.key) && !overlay.classList.contains("hidden")) upgradeCards.querySelectorAll("button")[Number(event.key) - 1]?.dispatchEvent(new MouseEvent("click")); }); window.addEventListener("keyup", event => keys.delete(event.key.toLowerCase()));
const gameElement = el<HTMLDivElement>("#game"); gameElement.addEventListener("mousemove", event => { if (!room || lastPhase !== "playing") return; const rect = gameElement.getBoundingClientRect(); room.send("aim", { x: ((event.clientX - rect.left) / rect.width) * GAME.width, y: ((event.clientY - rect.top) / rect.height) * GAME.height }); }); gameElement.addEventListener("mousedown", event => { if (event.button === 0 && room && lastPhase === "playing") { firing = true; beep(720, .025, "square"); } }); window.addEventListener("mouseup", event => { if (event.button === 0) firing = false; }); window.addEventListener("blur", () => { firing = false; keys.clear(); });
setInterval(() => { if (!room || lastPhase !== "playing") return; let dx = 0; let dy = 0; if (keys.has("a") || keys.has("arrowleft")) dx -= 1; if (keys.has("d") || keys.has("arrowright")) dx += 1; if (keys.has("w") || keys.has("arrowup")) dy -= 1; if (keys.has("s") || keys.has("arrowdown")) dy += 1; if (dx !== 0 || dy !== 0) room.send("input", { dx, dy }); if (firing) room.send("fire"); }, 1000 / GAME.serverHz);
